# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-09 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('display', models.CharField(max_length=36)),
                ('url', models.SlugField()),
                ('date_due', models.CharField(max_length=256)),
                ('date_todo', models.CharField(max_length=256)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('date_updated', models.DateTimeField(verbose_name='date updated')),
            ],
        ),
    ]
