# Generated by Django 3.2.7 on 2021-09-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_due',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_todo',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
