# Generated by Django 3.2.7 on 2021-09-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegboard', '0002_auto_20210909_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_due',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='date_todo',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
    ]
