# Generated by Django 3.2.7 on 2021-09-20 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegboard', '0006_delete_profile'),
        ('users', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=256)),
                ('username', models.CharField(blank=True, max_length=256)),
                ('display_name', models.CharField(blank=True, max_length=256)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pegboard.theme')),
            ],
        ),
    ]
