# Generated by Django 3.2.7 on 2021-09-20 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_socialprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialProfile',
        ),
    ]
